# Generated by Django 5.2.10 on 2026-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_tenantemailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment_request', 'Enrollment request'), ('enrollment_approved', 'Enrollment approved'), ('enrollment_rejected', 'Enrollment rejected'), ('announcement', 'Announcement'), ('ai_allowance', 'AI allowance')], max_length=40),
        ),
    ]
