# Generated by Django 5.2.10 on 2026-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment_request', 'Enrollment request'), ('enrollment_approved', 'Enrollment approved'), ('enrollment_rejected', 'Enrollment rejected'), ('announcement', 'Announcement'), ('ai_allowance', 'AI allowance'), ('account_created', 'Account created'), ('course_assigned', 'Course assigned')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tenantemailtemplate',
            name='type',
            field=models.CharField(choices=[('enrollment_request', 'New enrollment request (to admins)'), ('enrollment_approved', 'Enrollment approved (to student)'), ('enrollment_rejected', 'Enrollment declined (to student)'), ('account_created', 'Account created by admin (to student)'), ('course_assigned', 'Course assigned by admin (to student)'), ('credentials_reset', 'Password reset by admin (to student)')], max_length=40),
        ),
    ]
