# Generated by Django 5.2.10 on 2026-08-22 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_tenant_advanced_settings'),
        ('notifications', '0004_alter_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment_request', 'Enrollment request'), ('enrollment_approved', 'Enrollment approved'), ('enrollment_rejected', 'Enrollment rejected'), ('announcement', 'Announcement'), ('ai_allowance', 'AI allowance'), ('account_created', 'Account created'), ('course_assigned', 'Course assigned'), ('birthday', 'Birthday greeting'), ('birthday_digest', 'Birthday digest (to admins)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tenantemailtemplate',
            name='type',
            field=models.CharField(choices=[('enrollment_request', 'New enrollment request (to admins)'), ('enrollment_approved', 'Enrollment approved (to student)'), ('enrollment_rejected', 'Enrollment declined (to student)'), ('account_created', 'Account created by admin (to student)'), ('course_assigned', 'Course assigned by admin (to student)'), ('credentials_reset', 'Password reset by admin (to student)'), ('birthday_student', 'Birthday wish (to current student)'), ('birthday_past_student', 'Birthday wish (to past student)'), ('birthday_digest', "Today's birthdays (to admins)")], max_length=40),
        ),
        migrations.CreateModel(
            name='BirthdayDispatchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_date', models.DateField()),
                ('greeted_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_runs', to='core.tenant')),
            ],
            options={
                'ordering': ['-run_date'],
                'unique_together': {('tenant', 'run_date')},
            },
        ),
        migrations.CreateModel(
            name='BirthdayGreetingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('is_past_student', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_greetings', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_greetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'year'], name='notificatio_tenant__350134_idx')],
                'unique_together': {('user', 'year')},
            },
        ),
    ]
