# Generated by Django 5.2.10 on 2026-08-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaydispatchrun',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='birthdaydispatchrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthdaydispatchrun',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
