# Generated by Django 5.2.10 on 2026-08-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_birthdaydispatchrun_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment_request', 'Enrollment request'), ('enrollment_approved', 'Enrollment approved'), ('enrollment_rejected', 'Enrollment rejected'), ('announcement', 'Announcement'), ('ai_allowance', 'AI allowance'), ('account_created', 'Account created'), ('course_assigned', 'Course assigned'), ('birthday', 'Birthday greeting'), ('birthday_digest', 'Birthday digest (to admins)'), ('hackathon_registered', 'Hackathon registration'), ('hackathon_stage', 'Hackathon round update'), ('hackathon_result', 'Hackathon result'), ('hackathon_winner', 'Hackathon winner'), ('hackathon_announcement', 'Hackathon announcement')], max_length=40),
        ),
    ]
