# Generated by Django 5.2.10 on 2026-08-10 15:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import notebooks.nbformat_utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_tenant_ai_platform_monthly_tokens'),
        ('exams', '0014_course_sequential_chapter_unlock'),
        ('users', '0014_remove_studentprofile_primary_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('template_json', models.JSONField(blank=True, default=notebooks.nbformat_utils.empty_notebook)),
                ('packages', models.JSONField(blank=True, default=list)),
                ('time_limit_ms', models.PositiveIntegerField(default=30000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=512)),
                ('max_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=30)),
                ('is_timed', models.BooleanField(default=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('allow_resubmission', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('provisional_grading', models.CharField(choices=[('none', 'No instant score'), ('visible', 'Instant score from visible tests only'), ('all', 'Instant score from all tests (reveals hidden tests)')], default='visible', max_length=10)),
                ('show_results_to_students', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='exams.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to='exams.subject')),
                ('tenant', models.ForeignKey(help_text='Required: no notebook without tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='core.tenant')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebooks',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotebookDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='notebook_datasets/', validators=[django.core.validators.FileExtensionValidator(['csv', 'tsv', 'json', 'txt', 'xlsx', 'xls', 'parquet', 'npy', 'npz', 'zip'])])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='notebooks.notebook')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Notebook Dataset',
                'verbose_name_plural': 'Notebook Datasets',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotebookDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook_json', models.JSONField(blank=True, default=notebooks.nbformat_utils.empty_notebook)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='notebooks.notebook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_drafts', to='users.studentprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Notebook Draft',
                'verbose_name_plural': 'Notebook Drafts',
            },
        ),
        migrations.CreateModel(
            name='NotebookSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('notebook_json', models.JSONField(default=notebooks.nbformat_utils.empty_notebook)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('graded', 'Graded'), ('error', 'Engine error')], default='queued', max_length=20)),
                ('results', models.JSONField(blank=True, default=list)),
                ('execution_error', models.TextField(blank=True)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('passed_points', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('provisional_passed_points', models.PositiveIntegerField(default=0)),
                ('provisional_total_points', models.PositiveIntegerField(default=0)),
                ('provisional_results', models.JSONField(blank=True, default=list)),
                ('is_late', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('override_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_notebook_submissions', to=settings.AUTH_USER_MODEL)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='notebooks.notebook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_submissions', to='users.studentprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Notebook Submission',
                'verbose_name_plural': 'Notebook Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotebookCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_passed_points', models.PositiveIntegerField(default=0)),
                ('best_total_points', models.PositiveIntegerField(default=0)),
                ('best_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attempts_used', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='notebooks.notebook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_completions', to='users.studentprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_completions', to='core.tenant')),
                ('best_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notebooks.notebooksubmission')),
            ],
            options={
                'verbose_name': 'Notebook Completion',
                'verbose_name_plural': 'Notebook Completions',
            },
        ),
        migrations.CreateModel(
            name='NotebookTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('grade_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('source', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('is_hidden', models.BooleanField(default=True)),
                ('failure_hint', models.CharField(blank=True, max_length=500)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='notebooks.notebook')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Notebook Test',
                'verbose_name_plural': 'Notebook Tests',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['topic', 'status'], name='notebooks_n_topic_i_edeb88_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['course', 'status'], name='notebooks_n_course__ffa3bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='notebookdataset',
            constraint=models.UniqueConstraint(fields=('notebook', 'filename'), name='uniq_notebook_dataset_filename'),
        ),
        migrations.AddConstraint(
            model_name='notebookdraft',
            constraint=models.UniqueConstraint(fields=('notebook', 'student'), name='uniq_notebook_student_draft'),
        ),
        migrations.AddIndex(
            model_name='notebooksubmission',
            index=models.Index(fields=['notebook', 'student'], name='nb_submission_ns_idx'),
        ),
        migrations.AddIndex(
            model_name='notebooksubmission',
            index=models.Index(fields=['status'], name='nb_submission_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='notebooksubmission',
            constraint=models.UniqueConstraint(fields=('notebook', 'student', 'attempt_number'), name='uniq_notebook_student_attempt'),
        ),
        migrations.AddIndex(
            model_name='notebookcompletion',
            index=models.Index(fields=['notebook', 'student'], name='nb_completion_ns_idx'),
        ),
        migrations.AddConstraint(
            model_name='notebookcompletion',
            constraint=models.UniqueConstraint(fields=('notebook', 'student'), name='uniq_notebook_student_completion'),
        ),
    ]
