# Generated by Django 5.2.10 on 2026-08-13 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_zoomintegration_webhook_validation_until'),
        ('exams', '0014_course_sequential_chapter_unlock'),
        ('quiz', '0011_mocktest_max_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('create', 'New mock test'), ('modify', 'Modify an existing mock test')], default='create', max_length=20)),
                ('prompt', models.TextField(blank=True, default='')),
                ('input_mode', models.CharField(choices=[('text', 'Typed'), ('voice', 'Dictated')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('preview', 'Awaiting review'), ('applied', 'Applied'), ('failed', 'Failed'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('draft', models.JSONField(blank=True, default=dict)),
                ('revisions', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('generation_ms', models.PositiveIntegerField(default=0)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_summary', models.JSONField(blank=True, default=dict)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_mock_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_generation_jobs', to='exams.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('mock_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='quiz.mocktest')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Mock Test Generation Job',
                'verbose_name_plural': 'Mock Test Generation Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='mockgen_moc_tenant__54419e_idx'), models.Index(fields=['mock_test', 'kind'], name='mockgen_moc_mock_te_a4fb53_idx')],
            },
        ),
    ]
