# Generated by Django 5.2.10 on 2026-09-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_content_material_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='video_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending optimisation'), ('processing', 'Optimising'), ('ready', 'Ready to stream'), ('failed', 'Optimisation failed')], default='', max_length=20),
        ),
    ]
