# Generated by Django 5.2.10 on 2026-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_content_video_duration_seconds_content_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hls_playlist',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='content',
            name='hls_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending optimisation'), ('processing', 'Optimising'), ('ready', 'Ready to stream'), ('failed', 'Optimisation failed')], default='', max_length=20),
        ),
    ]
