# Generated by Django 5.2.10 on 2026-09-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_content_hls_playlist_content_hls_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hls_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='video_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
