# Generated by Django 5.2.10 on 2026-08-11 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_zoomintegration'),
        ('liveclass', '0001_initial'),
        ('users', '0014_remove_studentprofile_primary_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='attendance_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='attendance_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='zoom_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='zoom_meeting_uuid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='zoom_passcode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='zoom_registration_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='zoom_start_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='zoom_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='provider',
            field=models.CharField(choices=[('gmeet', 'Google Meet'), ('zoom', 'Zoom'), ('in_house', 'In-house Live')], default='gmeet', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveClassAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('zoom_participant_uuid', models.CharField(blank=True, default='', max_length=128)),
                ('zoom_registrant_id', models.CharField(blank=True, default='', max_length=128)),
                ('first_joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('join_count', models.PositiveIntegerField(default=0)),
                ('is_currently_in_call', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('partial', 'Partial'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('source', models.CharField(choices=[('portal', 'Portal join'), ('webhook', 'Zoom webhook'), ('report', 'Zoom report'), ('manual', 'Marked by admin')], default='portal', max_length=20)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='liveclass.liveclass')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_class_attendance', to='users.studentprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Live Class Attendance',
                'verbose_name_plural': 'Live Class Attendance',
                'ordering': ['-duration_minutes', 'display_name'],
                'indexes': [models.Index(fields=['live_class', 'status'], name='liveclass_l_live_cl_420ddf_idx'), models.Index(fields=['live_class', 'email'], name='liveclass_l_live_cl_d780d9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('live_class', 'student'), name='uniq_liveclass_student_attendance')],
            },
        ),
        migrations.CreateModel(
            name='LiveClassRegistrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('zoom_registrant_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('join_url', models.TextField(blank=True, default='')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='liveclass.liveclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_registrations', to='users.studentprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Live Class Registrant',
                'verbose_name_plural': 'Live Class Registrants',
                'indexes': [models.Index(fields=['live_class', 'email'], name='liveclass_l_live_cl_97f14c_idx')],
                'constraints': [models.UniqueConstraint(fields=('live_class', 'student'), name='uniq_liveclass_student_registrant')],
            },
        ),
    ]
