# Generated by Django 5.2.17 on 2026-08-19 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_zoomintegration_webhook_validation_until'),
        ('exams', '0015_topic_objectives'),
        ('quiz', '0011_mocktest_max_attempts'),
        ('users', '0014_remove_studentprofile_primary_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('tenant', 'Tenant'), ('global', 'Global')], default='tenant', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('llm_tagger', 'LLM tagger'), ('mockgen', 'Mock test builder'), ('coursegen', 'Course builder'), ('backfill', 'Backfill')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged into another concept'), ('archived', 'Archived')], default='active', max_length=10)),
                ('ontology_version', models.CharField(default='1', max_length=20)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_sources', to='intelligence.concept')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='exams.subject')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('topics', models.ManyToManyField(blank=True, related_name='concepts', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
            },
        ),
        migrations.CreateModel(
            name='ConceptAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_label', models.CharField(max_length=200)),
                ('alias_slug', models.CharField(max_length=220)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='intelligence.concept')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_aliases', to='exams.subject')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Concept Alias',
                'verbose_name_plural': 'Concept Aliases',
            },
        ),
        migrations.CreateModel(
            name='ConceptLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(default=1.0)),
                ('is_primary', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('llm_tagger', 'LLM tagger'), ('generator', 'Generator'), ('manual', 'Manual'), ('backfill', 'Backfill')], default='llm_tagger', max_length=20)),
                ('tagger_version', models.CharField(blank=True, default='', max_length=60)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='intelligence.concept')),
                ('mock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to='quiz.mocktestitem')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to='quiz.question')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Concept Link',
                'verbose_name_plural': 'Concept Links',
            },
        ),
        migrations.CreateModel(
            name='ItemStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('avg_time_seconds', models.FloatField(blank=True, null=True)),
                ('option_distribution', models.JSONField(blank=True, default=dict)),
                ('discrimination', models.FloatField(blank=True, null=True)),
                ('predicted_difficulty', models.CharField(blank=True, default='', max_length=20)),
                ('observed_difficulty', models.CharField(blank=True, default='', max_length=20)),
                ('difficulty_divergence', models.BooleanField(default=False)),
                ('stats_version', models.CharField(default='1', max_length=10)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('mock_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_stats', to='quiz.mocktestitem')),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_stats', to='quiz.question')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Item Stats',
                'verbose_name_plural': 'Item Stats',
            },
        ),
        migrations.CreateModel(
            name='LearnerConceptState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastery', models.FloatField(default=0.0)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('effective_evidence', models.FloatField(default=0.0)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('stability_days', models.FloatField(default=1.0)),
                ('retention', models.FloatField(default=0.0)),
                ('correct_streak', models.PositiveIntegerField(default=0)),
                ('single_attempts', models.PositiveIntegerField(default=0)),
                ('single_correct_w', models.FloatField(default=0.0)),
                ('multi_attempts', models.PositiveIntegerField(default=0)),
                ('multi_correct_w', models.FloatField(default=0.0)),
                ('transfer_gap', models.FloatField(blank=True, null=True)),
                ('misconception_counts', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(default='1', max_length=10)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_states', to='intelligence.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_states', to='users.studentprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Learner Concept State',
                'verbose_name_plural': 'Learner Concept States',
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('quiz_answer', 'Quiz answer (bank question)'), ('mock_bank_answer', 'Mock test answer (bank question)'), ('mock_item_answer', 'Mock test answer (inline item)'), ('practice_answer', 'Practice set answer')], max_length=20)),
                ('event_kind', models.CharField(choices=[('graded', 'Graded'), ('regraded', 'Regraded')], default='graded', max_length=10)),
                ('attempt_kind', models.CharField(blank=True, default='', max_length=10)),
                ('attempt_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_fraction', models.FloatField(default=0.0)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('response_digest', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(max_length=120, unique=True)),
                ('schema_version', models.CharField(default='1', max_length=10)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='quiz.answer')),
                ('item_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='quiz.mocktestanswer')),
                ('mock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='quiz.mocktestitem')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='quiz.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='users.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.subject')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Learning Event',
                'verbose_name_plural': 'Learning Events',
            },
        ),
        migrations.CreateModel(
            name='AITaggingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=20)),
                ('ontology_version', models.CharField(default='1', max_length=20)),
                ('model_ref', models.CharField(max_length=240)),
                ('result', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'AI Tagging Result',
                'verbose_name_plural': 'AI Tagging Results',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'content_hash', 'prompt_version', 'model_ref'), name='uniq_tagging_cache_entry')],
            },
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('tenant', 'subject', 'slug'), name='uniq_concept_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='conceptalias',
            constraint=models.UniqueConstraint(fields=('tenant', 'subject', 'alias_slug'), name='uniq_concept_alias'),
        ),
        migrations.AddConstraint(
            model_name='conceptlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question__isnull', False), ('mock_item__isnull', True)), models.Q(('question__isnull', True), ('mock_item__isnull', False)), _connector='OR'), name='conceptlink_exactly_one_item'),
        ),
        migrations.AddConstraint(
            model_name='conceptlink',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('concept', 'question'), name='uniq_conceptlink_question'),
        ),
        migrations.AddConstraint(
            model_name='conceptlink',
            constraint=models.UniqueConstraint(condition=models.Q(('mock_item__isnull', False)), fields=('concept', 'mock_item'), name='uniq_conceptlink_mock_item'),
        ),
        migrations.AddConstraint(
            model_name='itemstats',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question__isnull', False), ('mock_item__isnull', True)), models.Q(('question__isnull', True), ('mock_item__isnull', False)), _connector='OR'), name='itemstats_exactly_one_item'),
        ),
        migrations.AddIndex(
            model_name='learnerconceptstate',
            index=models.Index(fields=['tenant', 'concept'], name='intelligenc_tenant__0127ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnerconceptstate',
            constraint=models.UniqueConstraint(fields=('student', 'concept'), name='uniq_learner_concept_state'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['student', 'occurred_at'], name='intelligenc_student_4033fe_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['tenant', 'occurred_at'], name='intelligenc_tenant__601e89_idx'),
        ),
    ]
