# Generated by Django 5.2.17 on 2026-08-19 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_zoomintegration_webhook_validation_until'),
        ('exams', '0015_topic_objectives'),
        ('intelligence', '0001_initial'),
        ('quiz', '0013_mocktestanswer_ai_confidence_and_more'),
        ('users', '0014_remove_studentprofile_primary_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePracticeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice_enabled', models.BooleanField(default=True)),
                ('generation_enabled', models.BooleanField(default=True)),
                ('max_active_sets', models.PositiveIntegerField(default=3)),
                ('daily_xp_set_cap', models.PositiveIntegerField(default=3)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_config', to='exams.course')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Course Practice Config',
                'verbose_name_plural': 'Course Practice Configs',
            },
        ),
        migrations.CreateModel(
            name='PracticeGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deficit_kind', models.CharField(choices=[('low_mastery', 'Low mastery'), ('retention', 'Fading retention'), ('misconception', 'Repeated misconception'), ('cognitive_gap', 'Recall-application gap'), ('transfer_gap', 'Weak cross-concept transfer'), ('starter', 'Starter set (cold start)')], max_length=20)),
                ('deficit_signature', models.CharField(db_index=True, max_length=200)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('auto_apply', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('preview', 'Awaiting review'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('draft', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('generation_ms', models.PositiveIntegerField(default=0)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_summary', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_generation_jobs', to='exams.course')),
                ('target_concepts', models.ManyToManyField(blank=True, related_name='practice_generation_jobs', to='intelligence.concept')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Practice Generation Job',
                'verbose_name_plural': 'Practice Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deficit_kind', models.CharField(choices=[('low_mastery', 'Low mastery'), ('retention', 'Fading retention'), ('misconception', 'Repeated misconception'), ('cognitive_gap', 'Recall-application gap'), ('transfer_gap', 'Weak cross-concept transfer'), ('starter', 'Starter set (cold start)')], max_length=20)),
                ('deficit_signature', models.CharField(db_index=True, max_length=200)),
                ('target_misconception', models.CharField(blank=True, default='', max_length=300)),
                ('times_served', models.PositiveIntegerField(default=0)),
                ('times_answered', models.PositiveIntegerField(default=0)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_item', to='quiz.question')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_items', to='intelligence.practicegenerationjob')),
            ],
            options={
                'verbose_name': 'Generated Practice Item',
                'verbose_name_plural': 'Generated Practice Items',
            },
        ),
        migrations.CreateModel(
            name='PracticeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='suggested', max_length=15)),
                ('deficit_kind', models.CharField(choices=[('low_mastery', 'Low mastery'), ('retention', 'Fading retention'), ('misconception', 'Repeated misconception'), ('cognitive_gap', 'Recall-application gap'), ('transfer_gap', 'Weak cross-concept transfer'), ('starter', 'Starter set (cold start)')], max_length=20)),
                ('deficit_signature', models.CharField(db_index=True, max_length=200)),
                ('reason', models.JSONField(blank=True, default=dict)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score_correct', models.PositiveIntegerField(default=0)),
                ('score_total', models.PositiveIntegerField(default=0)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_sets', to='exams.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sets', to='users.studentprofile')),
                ('target_concepts', models.ManyToManyField(blank=True, related_name='practice_sets', to='intelligence.concept')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Practice Set',
                'verbose_name_plural': 'Practice Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('core', 'Core (at target difficulty)'), ('ladder_easy', 'Warm-up (one band easier)'), ('ladder_stretch', 'Stretch (one band harder)'), ('retention_interleave', 'Retention interleave')], default='core', max_length=25)),
                ('order', models.PositiveIntegerField(default=0)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('numerical_answer', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('practice_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intelligence.practiceset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_set_items', to='quiz.question')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Practice Set Item',
                'verbose_name_plural': 'Practice Set Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectiveEvalSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('spec', models.JSONField(default=dict)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval_spec', to='quiz.mocktestitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Subjective Eval Spec',
                'verbose_name_plural': 'Subjective Eval Specs',
            },
        ),
        migrations.AddIndex(
            model_name='practicegenerationjob',
            index=models.Index(fields=['tenant', 'status'], name='intelligenc_tenant__4de23b_idx'),
        ),
        migrations.AddIndex(
            model_name='practicegenerationjob',
            index=models.Index(fields=['deficit_signature', 'created_at'], name='intelligenc_deficit_1b655c_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceset',
            index=models.Index(fields=['student', 'status'], name='intelligenc_student_a169e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='practicesetitem',
            constraint=models.UniqueConstraint(fields=('practice_set', 'question'), name='uniq_practice_set_question'),
        ),
    ]
