# Generated by Django 5.2.17 on 2026-08-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_course_sequential_chapter_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='objectives',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
