# Generated by Django 5.2.17 on 2026-08-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_zoomintegration_webhook_validation_until'),
        ('exams', '0015_topic_objectives'),
        ('quiz', '0011_mocktest_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestitem',
            name='cognitive_type',
            field=models.CharField(blank=True, choices=[('recall', 'Recall'), ('application', 'Application'), ('multi_concept', 'Multi-concept / transfer')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mocktestitem',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mocktestitem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='mocktestitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_items', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='mocktestitem',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktestitem',
            name='tagging_status',
            field=models.CharField(blank=True, choices=[('', 'Untagged'), ('tagged', 'Tagged'), ('stale', 'Stale')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mocktestitem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_items', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='cognitive_type',
            field=models.CharField(blank=True, choices=[('recall', 'Recall'), ('application', 'Application'), ('multi_concept', 'Multi-concept / transfer')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tagging_status',
            field=models.CharField(blank=True, choices=[('', 'Untagged'), ('tagged', 'Tagged'), ('stale', 'Stale')], default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='mocktestitem',
            index=models.Index(fields=['topic', 'difficulty'], name='quiz_mockte_topic_i_a56b80_idx'),
        ),
    ]
