# Generated by Django 5.2.17 on 2026-08-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_mocktestitem_cognitive_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestanswer',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mocktestanswer',
            name='ai_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mocktestanswer',
            name='ai_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mocktestanswer',
            name='ai_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mocktestanswer',
            name='ai_suggested_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
