# Generated by Django 5.2.10 on 2026-08-09 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_aiquizquestion_topic'),
        ('core', '0020_tenant_ai_platform_monthly_tokens'),
        ('users', '0014_remove_studentprofile_primary_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('input_cost_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('output_cost_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('max_output_tokens', models.PositiveIntegerField(default=4000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform AI Model',
                'verbose_name_plural': 'Platform AI Models',
                'ordering': ['sort_order', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('groq', 'Groq (open-source models)'), ('openrouter', 'OpenRouter (free open-source models)'), ('together', 'Together AI (open-source models)'), ('ollama', 'Self-hosted Ollama'), ('custom', 'Custom OpenAI-compatible endpoint')], max_length=32)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('api_version', models.CharField(blank=True, default='2024-10-21', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform AI Provider',
                'verbose_name_plural': 'Platform AI Providers',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantAIAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('monthly_token_limit', models.PositiveIntegerField(default=0)),
                ('monthly_cost_limit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notify_at_percent', models.PositiveIntegerField(default=80)),
                ('last_notified_period', models.CharField(blank=True, default='', max_length=7)),
                ('last_notified_percent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tenant AI Allocation',
                'verbose_name_plural': 'Tenant AI Allocations',
            },
        ),
        migrations.AddField(
            model_name='aiusagerecord',
            name='feature',
            field=models.CharField(choices=[('chat', 'Doubt solver'), ('quiz', 'AI quiz'), ('coursegen', 'Course builder'), ('other', 'Other')], default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='aiusagerecord',
            name='platform_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='chatbot.platformaimodel'),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['source', 'created_at'], name='chatbot_aiu_source_d57db1_idx'),
        ),
        migrations.AddField(
            model_name='platformaimodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='chatbot.platformaiprovider'),
        ),
        migrations.AddField(
            model_name='tenantaiallocation',
            name='default_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_tenants', to='chatbot.platformaimodel'),
        ),
        migrations.AddField(
            model_name='tenantaiallocation',
            name='granted_models',
            field=models.ManyToManyField(blank=True, related_name='granted_to_tenants', to='chatbot.platformaimodel'),
        ),
        migrations.AddField(
            model_name='tenantaiallocation',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_allocation', to='core.tenant'),
        ),
        migrations.AddConstraint(
            model_name='platformaimodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_name'), name='uniq_platform_provider_model'),
        ),
    ]
