# Generated by Django 5.2.10 on 2026-08-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_aiusagerecord_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagerecord',
            name='feature',
            field=models.CharField(choices=[('chat', 'Doubt solver'), ('quiz', 'AI quiz'), ('coursegen', 'Course builder'), ('notebookgen', 'Notebook builder'), ('mockgen', 'Mock test builder'), ('other', 'Other')], default='chat', max_length=20),
        ),
    ]
