# Generated by Django 5.2.17 on 2026-08-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_aiusagerecord_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='tagging_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aiusagerecord',
            name='feature',
            field=models.CharField(choices=[('chat', 'Doubt solver'), ('quiz', 'AI quiz'), ('coursegen', 'Course builder'), ('notebookgen', 'Notebook builder'), ('mockgen', 'Mock test builder'), ('itemtag', 'Item tagging'), ('practicegen', 'Practice generator'), ('grading', 'Subjective grading'), ('other', 'Other')], default='chat', max_length=20),
        ),
    ]
