# Generated by Django 5.2.17 on 2026-08-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_aisettings_tagging_model_alter_aiusagerecord_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='grading_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
