# Generated by Django 5.2.10 on 2026-08-30 12:58

from django.db import migrations, models


def move_hackathon_postings_to_job(apps, schema_editor):
    """Hackathons now live in their own section, so no posting may keep that
    category. Reclassify the stragglers as ordinary jobs rather than leaving
    them with a value the model no longer allows."""
    Job = apps.get_model('jobs', 'Job')
    Job.objects.filter(category='hackathon').update(category='job')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_related_courses'),
    ]

    operations = [
        migrations.RunPython(
            move_hackathon_postings_to_job, migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], default='job', max_length=20),
        ),
    ]
