"""AI Mock Test Builder — the draft that sits between a prompt and a real paper.

Same rule as the course builder: **the AI never writes to the mock-test tables.**
A run only ever produces a :class:`MockTestGenerationJob` holding a JSON
``draft``. An admin reviews it, optionally hand-edits or refines it with another
instruction, and only an explicit "apply" call (with ``confirm=true``) turns it
into a real :class:`quiz.models.MockTest` plus its ``MockTestItem`` rows.

Statuses move strictly forward::

    pending → generating → preview → applied
                        ↘ failed        ↘ discarded

``preview`` is the only status an apply is accepted from, so one draft can never
be written twice.
"""
from django.db import models

from core.models import TimeStampedModel


class MockTestGenerationJob(TimeStampedModel):
    """One AI mock-test request plus the draft (paper) it produced."""

    # ── What the admin asked for ────────────────────────────────────────────
    # A brand-new paper, or an AI edit of a paper that already exists (whether
    # or not that paper was ever generated by AI).
    KIND_CREATE = 'create'
    KIND_MODIFY = 'modify'

    KIND_CHOICES = [
        (KIND_CREATE, 'New mock test'),
        (KIND_MODIFY, 'Modify an existing mock test'),
    ]

    STATUS_PENDING = 'pending'
    STATUS_GENERATING = 'generating'
    STATUS_PREVIEW = 'preview'
    STATUS_APPLIED = 'applied'
    STATUS_FAILED = 'failed'
    STATUS_DISCARDED = 'discarded'

    STATUS_CHOICES = [
        (STATUS_PENDING, 'Pending'),
        (STATUS_GENERATING, 'Generating'),
        (STATUS_PREVIEW, 'Awaiting review'),
        (STATUS_APPLIED, 'Applied'),
        (STATUS_FAILED, 'Failed'),
        (STATUS_DISCARDED, 'Discarded'),
    ]

    RUNNING_STATUSES = (STATUS_PENDING, STATUS_GENERATING)

    INPUT_TEXT = 'text'
    INPUT_VOICE = 'voice'
    INPUT_CHOICES = [(INPUT_TEXT, 'Typed'), (INPUT_VOICE, 'Dictated')]

    created_by = models.ForeignKey(
        'users.User',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='mock_generation_jobs',
    )
    # Set for every modify job, and back-filled on a create job once its draft
    # has been applied — so the builder can always show the work that produced
    # (or is about to change) the paper it is showing.
    mock_test = models.ForeignKey(
        'quiz.MockTest',
        on_delete=models.CASCADE,
        null=True, blank=True,
        related_name='generation_jobs',
    )
    # Optional syllabus grounding: generate strictly from a course's curriculum.
    course = models.ForeignKey(
        'exams.Course',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='mock_generation_jobs',
    )

    kind = models.CharField(max_length=20, choices=KIND_CHOICES, default=KIND_CREATE)
    prompt = models.TextField(blank=True, default='')
    input_mode = models.CharField(max_length=10, choices=INPUT_CHOICES, default=INPUT_TEXT)

    # The blueprint the admin filled in: sections, how many of each question
    # type, difficulty mix, duration, marks per type, language, apply mode…
    options = models.JSONField(default=dict, blank=True)

    # ── Which model produced it ─────────────────────────────────────────────
    provider = models.CharField(max_length=32, blank=True, default='')
    model = models.CharField(max_length=200, blank=True, default='')

    # ── Result ──────────────────────────────────────────────────────────────
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    # The reviewable paper — see mockgen.schema.normalize_mock.
    draft = models.JSONField(default=dict, blank=True)
    revisions = models.JSONField(default=list, blank=True)
    error = models.TextField(blank=True, default='')

    prompt_tokens = models.PositiveIntegerField(default=0)
    completion_tokens = models.PositiveIntegerField(default=0)
    total_tokens = models.PositiveIntegerField(default=0)
    estimated_cost_usd = models.DecimalField(max_digits=10, decimal_places=6, default=0)
    generation_ms = models.PositiveIntegerField(default=0)

    # ── Confirmation trail ──────────────────────────────────────────────────
    applied_at = models.DateTimeField(null=True, blank=True)
    applied_by = models.ForeignKey(
        'users.User',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='applied_mock_generation_jobs',
    )
    applied_summary = models.JSONField(default=dict, blank=True)

    class Meta:
        verbose_name = 'Mock Test Generation Job'
        verbose_name_plural = 'Mock Test Generation Jobs'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['tenant', 'status']),
            models.Index(fields=['mock_test', 'kind']),
        ]

    def __str__(self):
        return f'{self.get_kind_display()} — {self.status}'

    @property
    def is_reviewable(self):
        return self.status == self.STATUS_PREVIEW

    @property
    def is_running(self):
        """True while a background worker is (or is about to be) on this job.

        The studio polls until this flips false, so ``pending`` counts as
        running: the job is queued but no worker has claimed it yet.
        """
        return self.status in self.RUNNING_STATUSES

    def record_revision(self, action, detail=''):
        """Append an audit entry describing how the draft changed."""
        from django.utils import timezone

        entries = list(self.revisions or [])
        entries.append({
            'action': action,
            'detail': (detail or '')[:1000],
            'at': timezone.now().isoformat(),
        })
        # Keep the trail bounded — it is an aid, not an archive.
        self.revisions = entries[-25:]
