# Generated by Django 5.2.10 on 2026-08-11 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tenant_ai_platform_monthly_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret_encrypted', models.TextField(blank=True, default='')),
                ('webhook_secret_token_encrypted', models.TextField(blank=True, default='')),
                ('host_email', models.CharField(blank=True, default='', max_length=255)),
                ('use_registration', models.BooleanField(default=True, help_text='Register each enrolled student so they get a personal join link and attendance maps exactly to a student.')),
                ('pull_reports', models.BooleanField(default=True)),
                ('attendance_threshold_percent', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Zoom Integration',
                'verbose_name_plural': 'Zoom Integrations',
            },
        ),
    ]
