# Generated by Django 5.2.10 on 2026-08-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_zoomintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomintegration',
            name='webhook_validation_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
