# Generated by Django 5.2.10 on 2026-08-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_zoomintegration_webhook_validation_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
