# Generated by Django 5.2.10 on 2026-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tenant_feature_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='advanced_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
